Update Kubernetes dependencies to v1.36.0 (#9484)
* Update Kubernetes dependencies to v1.36.0

* Add PodGroupStates method into SharedLister interface

Reference PR: https://github.com/kubernetes/kubernetes/pull/137073

* Add PodGroups method into SharedLister interface

Reference PR: https://github.com/kubernetes/kubernetes/pull/136989

* Bump controller-runtime to be compatible with new kubernetes interface requirements

Current version raises compilation errors with 1.36 tools/cache library version, this change bumps controller runtime to have it adapted to the new requirements. Example error: vendor/sigs.k8s.io/controller-runtime/pkg/cache/multi_namespace_cache.go:363:9: cannot use handles (variable of struct type handlerRegistration) as "k8s.io/client-go/tools/cache".ResourceEventHandlerRegistration value in return statement: handlerRegistration does not implement "k8s.io/client-go/tools/cache".ResourceEventHandlerRegistration (missing method HasSyncedChecker)

There's no release tag containing a PR with a fix, this patch uses a specific commit hash to depend on, which should later be replaced with a correct, non-pseudo version

* Adapt to DRA scheduler interface changes in 1.36

Reference PR: https://github.com/kubernetes/kubernetes/pull/137897

* Adapt resourceclaim.IsForPod/resourceclaim.IsReservedForPod usages in DRA autoscaling

* Adapt DRA snapshot claim tracker to new scheduler API

Reference PR: https://github.com/kubernetes/kubernetes/pull/137897

* Expose NoOp PodGroupStateLister interfaces for snapshot stores

* Add NoOp PodGroupLister for DRA snapshot

Reference PR: https://github.com/kubernetes/kubernetes/pull/136989

* Register no-op SharedDraManager when DRA is disabled to prevent panic in scheduler plugin

* Adapt to NodeDeclaredFeatures interface changes

This change also changes the assumptions in couple tests as node declared features graduated to beta in 1.36 enabling intergration by default

* Add comments to missing exported methods

* Bump golang version to 1.26 to unblock CI

* Add copyright headers to no-op shared DRA manager module

* Patch comment placement in delta cluster snapshot