Bump controller-runtime to be compatible with new kubernetes interface requirements
Current version raises compilation errors with 1.36 tools/cache library version, this change bumps controller runtime to have it adapted to the new requirements. Example error: vendor/sigs.k8s.io/controller-runtime/pkg/cache/multi_namespace_cache.go:363:9: cannot use handles (variable of struct type handlerRegistration) as "k8s.io/client-go/tools/cache".ResourceEventHandlerRegistration value in return statement: handlerRegistration does not implement "k8s.io/client-go/tools/cache".ResourceEventHandlerRegistration (missing method HasSyncedChecker)

There's no release tag containing a PR with a fix, this patch uses a specific commit hash to depend on, which should later be replaced with a correct, non-pseudo version