Protect concurrent map access in ScaleDownCandidatesDelayProcessor
The ScaleDownCandidatesDelayProcessor uses three maps (scaleUps, scaleDowns,
scaleDownFailures) that are accessed concurrently without synchronization,
causing occasional "fatal error: concurrent map read and map write" panics
like the one logged below:

```
I0125 23:53:49.284467      94 aws_manager.go:169] DeleteInstances was called: scheduling an ASG list refresh for next main loop evaluation
fatal error: concurrent map read and map write

goroutine 64 [running]:
internal/runtime/maps.fatal({0x6a1d287?, 0x358cfec?})
    /usr/local/go/src/runtime/panic.go:1058 +0x20
k8s.io/autoscaler/cluster-autoscaler/processors/scaledowncandidates.(*ScaleDownCandidatesDelayProcessor).GetScaleDownCandidates.func1(0x4004791290, 0x0, {0x69a3ae1, 0xb})
    /build/cluster-autoscaler/processors/scaledowncandidates/scale_down_candidates_delay_processor.go:64 +0x74
k8s.io/autoscaler/cluster-autoscaler/processors/scaledowncandidates.(*ScaleDownCandidatesDelayProcessor).GetScaleDownCandidates(0x40047a2150, 0x4000644008, {0x4041b70008, 0x3bc, 0x22f?})
    /build/cluster-autoscaler/processors/scaledowncandidates/scale_down_candidates_delay_processor.go:77 +0x2dc
k8s.io/autoscaler/cluster-autoscaler/processors/scaledowncandidates.(*combinedScaleDownCandidatesProcessor).GetScaleDownCandidates(0xad47200?, 0x4000644008, {0x40405b8008?, 0x0?, 0x0?})
    /build/cluster-autoscaler/processors/scaledowncandidates/scale_down_candidates_processor.go:59 +0x6c
k8s.io/autoscaler/cluster-autoscaler/core.(*StaticAutoscaler).RunOnce(0x4001211860, {0x19035c?, 0x1d091a7098197?, 0xad46400?})
    /build/cluster-autoscaler/core/static_autoscaler.go:575 +0x1f20
k8s.io/autoscaler/cluster-autoscaler/loop.RunAutoscalerOnce({0xe351712f7158, 0x4001211860}, 0x4000858230, {0xad46400?, 0x39fcb2bac404?, 0xad46400?})
    /build/cluster-autoscaler/loop/run.go:36 +0x80
main.run(0x4000858230, {0x7478858, 0x400052d170})
    /build/cluster-autoscaler/main.go:324 +0x2f0
main.main.func2({0x0?, 0x0?})
    /build/cluster-autoscaler/main.go:433 +0x28
created by k8s.io/client-go/tools/leaderelection.(*LeaderElector).Run in goroutine 1
    /go/pkg/mod/k8s.io/client-go@v0.34.2/tools/leaderelection/leaderelection.go:220 +0xe4

....

goroutine 272269381 [runnable]:
k8s.io/autoscaler/cluster-autoscaler/core/scaledown/deletiontracker.(*NodeDeletionTracker).EndDeletion(0x4004e7c550, {0x4002dd7a80, 0x34}, {0x407b582d80, 0x1d}, {{0x0?, 0x0?}, 0x404f3cbeb0?, 0x0?})
    /build/cluster-autoscaler/core/scaledown/deletiontracker/nodedeletiontracker.go:99 +0x26c
k8s.io/autoscaler/cluster-autoscaler/core/scaledown/actuation.RegisterAndRecordSuccessfulScaleDownEvent(0x4000644008, {0x74675e0, 0x4002ec4740}, 0x40532b9808, {0x74905e0, 0x404e8f4440}, 0x0, 0x4004e7c550)
    /build/cluster-autoscaler/core/scaledown/actuation/delete_in_batch.go:227 +0x2c4
k8s.io/autoscaler/cluster-autoscaler/core/scaledown/actuation.(*NodeDeletionBatcher).deleteNodesAndRegisterStatus(0x40011df8c0, {0x40920dcd10, 0x1, 0x4090e84ba0?}, {0x4002dd7a80, 0x34}, 0x0)
    /build/cluster-autoscaler/core/scaledown/actuation/delete_in_batch.go:95 +0x118
created by k8s.io/autoscaler/cluster-autoscaler/core/scaledown/actuation.(*NodeDeletionBatcher).AddNodes in goroutine 272269380
    /build/cluster-autoscaler/core/scaledown/actuation/delete_in_batch.go:75 +0xd4

```